
service: zoom-api-service
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  profile: serverless
functions:
  zoom:
    handler: handler.zoom
    events:
      - http:
          path: zoom
          method: get